version : "3"
services:
  nginx-dev:
    container_name: nginx-dev
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ec2-user/app/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

  redis-dev:
    container_name: redis-dev
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    volumes:
      - /home/ec2-user/app/data/redis:/data

  dadok-dev-blue:
    container_name: dadok-dev-blue
    image: ${DOCKER_DEV_REPO}
    expose:
      - "8080"
    working_dir: /app
    volumes:
      - /home/ec2-user/logs:/app/logs
    depends_on:
      - nginx-dev
    restart: always
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      FRONT_DOMAIN: ${FRONT_DOMAIN}

      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DRIVER_CLASS_NAME: ${DRIVER_CLASS_NAME}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      HIBERNATE_FORMAT_SQL: ${HIBERNATE_FORMAT_SQL}
      HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      HIBERNATE_DEFAULT_BATCH_FETCH_SIZE: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE}
      ENABLE_JPA_OPEN_IN_VIEW: ${ENABLE_JPA_OPEN_IN_VIEW}
      DATABASE_NAME: ${DATABASE_NAME}
      ENABLE_P6SPY: ${ENABLE_P6SPY}


      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_PATH: ${KAKAO_REDIRECT_PATH}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_REDIRECT_PATH: ${NAVER_REDIRECT_PATH}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
      REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS}

      KAKAO_BOOK_BASE_URI: ${KAKAO_BOOK_BASE_URI}
      KAKAO_SCHEME: ${KAKAO_SCHEME}

      SERVER_HOST: ${SERVER_HOST}

      SLACK_OAUTH_TOKEN: ${SLACK_OAUTH_TOKEN}
      SLACK_ERROR_CHANNEL_ID: ${SLACK_ERROR_CHANNEL_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  dadok-dev-green:
    container_name: dadok-dev-green
    image: ${DOCKER_DEV_REPO}
    expose:
      - "8080"
    working_dir: /app
    volumes:
      - /home/ec2-user/logs:/app/logs
    depends_on:
      - nginx-dev
    restart: always
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      FRONT_DOMAIN: ${FRONT_DOMAIN}

      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DRIVER_CLASS_NAME: ${DRIVER_CLASS_NAME}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      HIBERNATE_FORMAT_SQL: ${HIBERNATE_FORMAT_SQL}
      HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      HIBERNATE_DEFAULT_BATCH_FETCH_SIZE: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE}
      ENABLE_JPA_OPEN_IN_VIEW: ${ENABLE_JPA_OPEN_IN_VIEW}
      DATABASE_NAME: ${DATABASE_NAME}
      ENABLE_P6SPY: ${ENABLE_P6SPY}


      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_PATH: ${KAKAO_REDIRECT_PATH}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_REDIRECT_PATH: ${NAVER_REDIRECT_PATH}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
      REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS}

      KAKAO_BOOK_BASE_URI: ${KAKAO_BOOK_BASE_URI}
      KAKAO_SCHEME: ${KAKAO_SCHEME}

      SERVER_HOST: ${SERVER_HOST}

      SLACK_OAUTH_TOKEN: ${SLACK_OAUTH_TOKEN}
      SLACK_ERROR_CHANNEL_ID: ${SLACK_ERROR_CHANNEL_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}