spring:
  profiles:
    include:
      - db
      - security
      - aws
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import: optional:file:.env[.properties]
  lifecycle:
    timeout-per-shutdown-phase: 5s
server:
  shutdown: graceful

  host: ${SERVER_HOST}