spring:
  profiles:
    include:
      - db
      - security
      - aws
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import: optional:file:.env[.properties]

server:
  shutdown: graceful
  port : ${SERVER_PORT}