spring:
  profiles:
    include:
      - db
      - security
      - aws
      - api
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import: optional:file:.env[.properties]
  lifecycle:
    timeout-per-shutdown-phase: 5s
server:
  shutdown: graceful

  host: ${SERVER_HOST}

logging:
  level:
    com:
      dadok:
        gaerval: DEBUG

    org.springframework.web: DEBUG

    reactor:
      netty:
        http:
          client:
            reactor.netty.http.client.HttpClient: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG


slack:
  oauth-token: ${SLACK_OAUTH_TOKEN}
  error-channel-id: ${SLACK_ERROR_CHANNEL_ID}
