search-api-provider:
    # kakao
    api-key: ${KAKAO_CLIENT_ID}
    scheme: ${KAKAO_SCHEME}
    base-uri: ${KAKAO_BOOK_BASE_URI}
    # aladin
    ttb-key: ${TTB_KEY}
    best-seller-base-uri : ${ALADIN_BOOK_BASE_URI}