name: develop ci-cd

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: set up environment Variable
        run: |
          echo "${{secrets.TEST_ENV_FILE }}" > ./.env
          echo "${{secrets.APPLICATION_TEST}}" >> ./src/test/resources/application-test.yml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradle permission
        run: chmod +x ./gradlew

      - name: test with Gradle
        run: ./gradlew test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'

      - name: Add coverage comment to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/jacoco/test_report/test_report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 0
          update-comment: true
          title: "Jacoco Test Coverage Reports"
